<p>Hi <?= e($this->participant->fornavn);?>,</p>

<p>
  You are one of the participants who qualify for certain discounts at Fastaval. Therefore you need to have a photo on
  your name tag.
</p>

<p>
  It seems you have not yet uploaded a photo for your name tag. Without a photo on your name tag, you can't use it for
  discounts, so we kindly remind you that you need to have uploaded a photo by <strong><?=$this->signup_end_time?></strong>.
  You can upload a photo using the following link:
</p>

<p><a href="<?= $this->link;?>"><?= $this->link;?></a></p>

<p>
  If you have already attempted to upload a photo with no success, our apologies. Please contact 
  <a href="mailto:info@fastaval.dk">info@fastaval.dk</a> and let us know of the problem - and remember to include your
  photo, so we can get things fixed.
</p>

<p>
  Many greetings<br/>
  Fastaval
</p>
