<html>
<style>
body { padding: 2rem; background-color: #d4d1d1 }
</style>
</html>
<body>
    <img src="https://www.fastaval.dk/wp-content/uploads/2021/01/Hjemmeside-header.jpg" alt="Fastaval 2021 logo"/>
    <p>Here are the links to voting for <strong><?= e($this->title);?></strong>. One link for the gamemaster, the rest for players. Please distribute to your players to match who participated.</p>

    <ol><?php foreach ($this->team_votes as $vote) : ?>
    <li>Link: <a href="<?= $this->url('activity_specific_vote', ['code' => $vote['code']]);?>"><?= $this->url('activity_specific_vote', ['code' => $vote['code']]);?></a></li>

    <?php endforeach;?>
    </ol>

    <p>Please remind your players to vote no later than Sunday at 18.00 CEST. Thank you for helping Fastaval.</p>

    <p>Thank you!</p>
    <p>Fastaval 2021</p>
</body>
