<div id="content" style="max-width: 800px; margin: auto; font-family: Arial, Helvetica, sans-serif;">
  <style>
    div.section {
      max-width: 81.5%;
      margin: auto;

      background-color: #f9ad1b;
      padding: 1rem;
      border-radius: 10px;

      margin-bottom: 2rem;
    }

    div.section h2 {
      text-align: center;
      margin-top: 0;
    }

    div.section table {
      margin: auto;
    }
  </style>

  <img src="https://infosys.fastaval.dk/img/banner-2024.png" style="width: 100%"/>
  
<div class="section">
  <h2>Dear <?=$this->name?>,</h2>
  
  <p>
    Fastaval is getting close, the excitement is building, and now your program is ready! But first, we have some
    important info for you.
  </p>
</div>

<div class="section">
  <h2>Practical information</h2>
  
  <p>
    You can find practical information about fx. transport, rules and opening hours at:</br> 
    <a href="https://www.fastaval.dk/en/praktisk/praktiske-informationer/">https://www.fastaval.dk/en/praktisk/praktiske-informationer/</a>.
  </p>
  
  <p>
    If you have questions regarding Fastaval, you can also contact <a href="mailto:info@fastaval.dk">info@fastaval.dk</a>
  </p>
  
  <p>
    If you need to talk to a safety-host, they can be contacted at <strong>+45&nbsp;93&nbsp;90&nbsp;35&nbsp;67</strong>.</br>
    You can read more about the safety-hosts and safety at Fastaval at:
    <a href="https://www.fastaval.dk/en/tryghed/">https://www.fastaval.dk/en/tryghed/</a>.
  </p>
  
  <p>
    Additionally, you can always contact the general on duty at: <strong>+45&nbsp;93&nbsp;90&nbsp;35&nbsp;69</strong>
  </p>
</div>
  
<div class="section">
  <h2>New to Fastaval</h2>
  
  <p>
    If you are new to Fastaval (or just need a refresher), you can join the intro-tour. Here you can ask all your
    questions and get to know other new participants. The tour begins at the information in the common area, and runs at:
  </p>
  
  <table>
    <tr>
      <td>Wednesday:</td><td>5:30 pm</td>
    </tr>
    <tr>
      <td>Thu - Sat:</td><td>10:00 am</td>
    </tr>
  </table>
</div>

<div class="section">
  <h2>Check in when you arrive</h2>
  
  <p>
    To check in at Fastaval you nedd to go to the Info at the main entrance to Mariagerfjord High School and receive a
    wristband, which grants you access to Fastaval. The info is open everyday:
  </p>
  
  <table>
    <tr>
      <td>Wednesday:</td><td>3:00 pm - 8:30 pm</td>
    </tr>
    <tr>
      <td>Thu - Sat:</td><td>09:30 am - 8:30 pm</td>
    </tr>
    <tr>
      <td>Sunday:</td><td>09:30 am - 5:00 pm</td>
    </tr>
  </table>
  
  <p>
    If you signed up before the deadline, you will also receive a name tag upon check-in.
  </p>
  
  <p>
    At the info you can also obtain a number of different badges that communicate your spoken languages, your pronouns
    and sobriety to other participants.
  </p>
</div>

<div class="section">
  <h2>Clean-up</h2>
  
  <p>
    We would like to see as many participants as possible at the clean-up on Monday April 1st. Just an hour of your
    time is a big help to our tired organizers, and helps everyone get home in good shape.
  </p>
  
  <p>
    Please show up and help if at all possible, it means the world to us.
  </p>
</div>
  
<div class="section">
  <h2>The Hero Force</h2>
  
  <p>
    If you have signed up for the hero force, you can view your assigned task(s) in your program or in the app (see below).
  </p>
  
  <p>
    If you can already now see that you will be unable to help during your assigned task, please contact the hero force
    coordinators at <a href="mailto:heltestyrken@fastaval.dk">heltestyrken@fastaval.dk</a> - and we'll find a solution.
  </p>
  
  <p>
    If you become unable to help out during Fastval, due to sickness and the like, please tell us as soon as possible,
    so we can make arrangements to cover your task.
  </p>
  
  <p>
    During Fastaval, you can contact Magnus and Christoffer, the coordinators of the hero force, at
    <strong>+45&nbsp;93&nbsp;90&nbsp;35&nbsp;68</strong>.
  </p>
</div>

<div class="section">
  <h2>Your Fastaval program</h2>
  
  <p>
    You can access your assigned activities, games, sleeping spot and hero tasks by visiting:
    <br><a href="https://infosys.fastaval.dk/deltager/showsignup/<?=$this->id?>">
      https://infosys.fastaval.dk/deltager/showsignup/<?=$this->id?>
    </a>
  </p>
  
  <p>
    Your participant numbers is: <strong><?=$this->id?></strong><br>
  </p>
  
  <p>
    Your personal code is: <strong><?=$this->code?></strong>
  </p>
  
  <p>
    If you are interested in the other activities at Fastaval, you can find them in the program here:</br>
    <a href="https://docs.google.com/spreadsheets/d/1eyzvLbd9JcoXsp6ari1LLbBDENE2SU_V">Program for Fastaval 2024</a>
  </p>
</div>

<div class="section">
  <h2>The Fastaval App</h2>
  
  <p>
    In our app you can view your program, food tickets, sleeping spot and all practical information related to your
    sign-up, as well as receive notifications from Fastaval. You log into the app using the same participant number and
    code as above. We encourage all participants to use the app to keep them selves up-to-date at Fastaval.
  </p>
  
  <p>
    You can find the app by searching for “Fastaval” in your Play/App store or by using the following links:
  </p>
  
  <p>
    <a href="https://play.google.com/store/apps/details?id=dk.alea.fastaval.fastaval_app">Google Play</a>
  </p>
  
  <p>
    <a href="https://apps.apple.com/us/app/fastavappen/id6445799103">App Store</a>
  </p>
</div>

<div class="section">
  <h2>Finally</h2>
  
  <p>We're looking forward to see you at Fastaval 2024!</p>
  
</div>

<img src="https://infosys.fastaval.dk/img/logo-plain-text.png" width="200" style="display: block; margin: auto;"/>

</div>