<div id="content" style="max-width: 800px; margin: auto; font-family: Arial, Helvetica, sans-serif;">
  <style>
    div.section {
      max-width: 81.5%;
      margin: auto;

      background-color: #f9ad1b;
      padding: 1rem;
      border-radius: 10px;

      margin-bottom: 2rem;
    }

    div.section h2 {
      text-align: center;
      margin-top: 0;
    }

    div.section table {
      margin: auto;
    }
  </style>

  <img src="https://infosys.fastaval.dk/img/banner-2024.png" style="width: 100%"/>
  
<div class="section">
  <h2>Kære <?=$this->name?>,</h2>
  
  <p>
    Nu nærmer Fastaval sig, spændingen stiger og det er tid til dit årlige Fastaval program! Men først lidt vigtig
    information.
  </p>
</div>

<div class="section">
  <h2>Praktisk information</h2>
  
  <p>
    Du kan finde praktisk information om fx. transport, ordensregler og åbningstider på:</br> 
    <a href="https://www.fastaval.dk/praktisk/praktiske-informationer/">https://www.fastaval.dk/praktisk/praktiske-informationer/</a>.
  </p>
  
  <p>
    Har du spørgsmål til Fastaval, skal du kontakte <a href="mailto:info@fastaval.dk">info@fastaval.dk</a>
  </p>
  
  <p>
    Hvis du har brug for en tryghedsvært kan du kontakte dem på <strong>+45&nbsp;93&nbsp;90&nbsp;35&nbsp;67</strong>.</br>
    Du kan læse mere om tryghedsværterne og tryghed på Fastaval her:
    <a href="https://www.fastaval.dk/tryghed/">https://www.fastaval.dk/tryghed/</a>.
  </p>
  
  <p>
    Derudover kan du altid komme i kontakt med Vagthavende General på: <strong>+45&nbsp;93&nbsp;90&nbsp;35&nbsp;69</strong>
  </p>
</div>
  
<div class="section">
  <h2>Ny på Fastaval</h2>
  
  <p>
    Hvis du er ny på Fastaval (eller bare har brug for en opfrisker), kan du komme med på introtur. Her kan du stille alle
    dine spørgsmål og lære andre nye deltagere at kende. Turen starter ved Informationen i fællesområdet, og afholdes:
  </p>
  
  <table>
    <tr>
      <td>Onsdag:</td><td>17:30</td>
    </tr>
    <tr>
      <td>Tor-Lør:</td><td>10:00</td>
    </tr>
  </table>
</div>

<div class="section">
  <h2>Tjek ind når du ankommer</h2>
  
  <p>
    Du tjekker ind på Fastaval i Infoen ved hovedindgangen på Mariagerfjord Gymnasium og får et armbånd, der giver adgang
    til Fastaval. Infoen har åbent hver dag:
  </p>
  
  <table>
    <tr>
      <td>Onsdag:</td><td>15:00 - 20:30</td>
    </tr>
    <tr>
      <td>Tor-Lør:</td><td>09:30 - 20:30</td>
    </tr>
    <tr>
      <td>Søndag:</td><td>09:30 - 17:00</td>
    </tr>
  </table>
  
  <p>
    Har du tilmeldt dig inden for deadlinen, får du også et navneskilt ved tjek-ind.
  </p>
  
  <p>
    Ved Informationen kan du også hente forskellige typer badges, som hjælper med at kommunikere dit sprog, pronomier
    eller din ædru-tilstand til andre deltagere.
  </p>
</div>

<div class="section">
  <h2>Nedpilning</h2>
  
  <p>
    Vi ser gerne at alle deltagere og arrangører giver en hånd med til nedpilning mandag d. 1. April. Bare en times
    oprydning kan gøre underværker og hjælpe vores trættere arrangører med at komme hjem i god tid.
  </p>
  
  <p>
    Vi sætter virkelig pris på jeres hjælp, og håber, at så mange af jer som muligt, vil give en hånd.
  </p>
</div>
  
<div class="section">
  <h2>Heltestyrken</h2>
  
  <p>
    Hvis du er tilmeldt Heltestyrken kan du også se din tildelte opgave i dit program og i appen.
  </p>
  
  <p>
    Hvis du allerede nu kan se, at du IKKE kan møde op til din opgave, bedes du skrive til de heltestyrkeansvarlige,
    på <a href="mailto:heltestyrken@fastaval.dk">heltestyrken@fastaval.dk</a> - så finder vi en løsning.
  </p>
  
  <p>
    Skulle det under Fastaval ske, at du ikke er i stand til at tage din opgave, f.eks. ved sygdom, så fortæl os det,
    så snart det er muligt. Så har vi nemlig tid til at finde en, der kan tage over.
  </p>
  
  <p>
    Du kan komme i kontakt med Magnus og Christoffer, som er ansvarlige for Heltestyrken,
    på <strong>+45&nbsp;93&nbsp;90&nbsp;35&nbsp;68</strong> under Fastaval.
  </p>
</div>

<div class="section">
  <h2>Dit Fastavalprogram</h2>
  
  <p>
    Du får adgang til at se dine tildelte aktiviteter, spil, overnatningsplads samt helteopgaver ved at gå ind på: 
    <br><a href="https://infosys.fastaval.dk/deltager/showsignup/<?=$this->id?>">
      https://infosys.fastaval.dk/deltager/showsignup/<?=$this->id?>
    </a>
  </p>
  
  <p>
    Dit deltagernummer er <strong><?=$this->id?></strong><br>
  </p>
  
  <p>
    Du skal bruge din personlige kode for at få adgang - den er: <strong><?=$this->code?></strong>
  </p>
  
  <p>
    Er du interesseret i andre aktiviteter kan du se dem i årets program:</br>
    <a href="https://docs.google.com/spreadsheets/d/1eyzvLbd9JcoXsp6ari1LLbBDENE2SU_V">Program for Fastaval 2024</a>
  </p>
</div>

<div class="section">
  <h2>Fastavals App</h2>
  
  <p>
    I appen kan du se dit program, madbilletter, sovelokale, kort og få notifikationer fra Fastaval. Du logger ind på
    appen med samme deltagernummer og kode som i denne mail. Vi opfordrer alle deltagere til at bruge appen til at holde
    sig up-to-date på Fastaval.
  </p>
  
  <p>
    Du kan finde vore app ved at søge på Fastaval i din Play/App store eller med følgende links:
  </p>
  
  <p>
    <a href="https://play.google.com/store/apps/details?id=dk.alea.fastaval.fastaval_app">Google Play</a>
  </p>
  
  <p>
    <a href="https://apps.apple.com/us/app/fastavappen/id6445799103">App Store</a>
  </p>
</div>

<div class="section">
  <h2>Til sidst</h2>
  
  <p>Vi glæder os til at se dig til Fastaval 2024!</p>
  
</div>

<img src="https://infosys.fastaval.dk/img/logo-plain-text.png" width="200" style="display: block; margin: auto;"/>

</div>